apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: hknh6htvg-dotnet-basic 
  janus-idp.io/tekton: hknh6htvg-dotnet-basic
  backstage.io/kubernetes-id: hknh6htvg-dotnet-basic
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: hknh6htvg-dotnet-basic
resources:
  - application-dev.yaml
  - application-stage.yaml
  - application-prod.yaml